name: Build for x86_64

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      target_version:
        description: Release target version
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get architecture
        id: get_arch
        run: |
          echo "Architecture: $(arch)"
          echo "arch=$(arch)" >> $GITHUB_OUTPUT
      - name: Build
        run: |
          docker run --rm --env STDOUT=1 --env GLIBC_VERSION=${{ github.event.inputs.target_tag }} pman0214/glibc-builder ${{ github.event.inputs.target_tag }} /usr/glibc-compat > glibc-bin-${{ github.event.inputs.target_tag }}-${{ steps.get_arch.outputs.arch }}.tar.gz
      - name: Archive build output
        uses: actions/upload-artifact@v4
        with:
          name: built-glibc-bin
          path: glibc-bin-${{ github.event.inputs.target_tag }}-${{ steps.get_arch.outputs.arch }}.tar.gz
          retention-days: 3
